# Generated by Django 4.1.7 on 2023-03-29 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 29, 17, 28, 52, 283669)),
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 29, 17, 28, 52, 283669)),
        ),
        migrations.AlterField(
            model_name='signup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 29, 17, 28, 52, 282690)),
        ),
    ]
