# Generated by Django 4.1.7 on 2023-04-26 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 26, 17, 34, 31, 913306))),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 26, 17, 34, 31, 913306))),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
