# Generated by Django 4.1.7 on 2023-04-28 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_blog_created_alter_blog_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='updated',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 28, 13, 52, 47, 440214)),
        ),
    ]
