# Generated by Django 4.1.7 on 2023-04-28 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_remove_blog_updated_alter_blog_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 28, 13, 56, 48, 974058)),
        ),
    ]
